# .github/workflows/python-test.yml
name: Python Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"] # Test against supported range

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup uv
      uses: astral-sh/setup-uv@v5 

    - name: Install dependencies with uv
      run: |
        uv venv
        uv sync --dev

    - name: Run tests with coverage
      run: |
        uv run pytest --cov=src/corona_network_standard --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Optional: Add if repo is private
        slug: acedrew/corona-network-standard # Explicitly set repo slug
        fail_ci_if_error: true # Optional: Fail CI if Codecov upload fails
